#!/usr/bin/env python3
"""
══════════════════════════════════════════════════════════════════════════════
  PROSPERITY ROUND 2 — BACKTESTING ENGINE
  Author: generated by Claude
  Usage:
      python backtest.py --algo trader.py [--log submission.log]
                         [--data-dir /path/to/csvs] [--maf 0] [--verbose]
                         [--days -1 0 1] [--report report.html]

  What it does:
    1. Loads the 6 CSV data files (prices + trades, days -1/0/1).
    2. Builds a mock `datamodel` so your algo imports cleanly with zero changes.
    3. Replays every price-tick (every 100 timestamps) in chronological order,
       calling Trader.run() exactly as the Prosperity engine would.
    4. Matches your algo's orders against the live order book using the same
       price-time priority rules as Prosperity.
    5. If a .log file is supplied, compares your backtest PnL against the actual
       submission PnL tick-by-tick and flags divergences.
    6. Computes the Manual Challenge (Invest & Expand) optimum allocation.
    7. Prints a rich terminal report and (optionally) saves an HTML report.

  Notes on fill model:
    - Orders are matched against the FULL 3-level order book each tick.
    - Passive orders: filled if market crosses our posted price.
    - Aggressive orders (price > best ask or price < best bid): filled at the
      MARKET price (you can't get a better fill than what's available).
    - Position limits (80 per product) are enforced; excess qty is clipped.
    - The +25% MAF volume is NOT in the CSV data, so MAF is deducted from PnL
      as a one-time fee but volume uplift is noted only as an estimate.
══════════════════════════════════════════════════════════════════════════════
"""

import argparse
import ast
import copy
import importlib.util
import io
import json
import math
import os
import sys
import textwrap
import traceback
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

# ─────────────────────────────────────────────────────────────────────────────
#  MOCK DATAMODEL  (mirrors the Prosperity datamodel exactly)
# ─────────────────────────────────────────────────────────────────────────────

Symbol   = str
Product  = str
Position = int


@dataclass
class Order:
    symbol: Symbol
    price: int
    quantity: int          # positive = buy, negative = sell

    def __repr__(self):
        side = "BUY" if self.quantity > 0 else "SELL"
        return f"Order({self.symbol}, {side} {abs(self.quantity)}@{self.price})"


@dataclass
class OrderDepth:
    buy_orders:  Dict[int, int] = field(default_factory=dict)   # price → qty (positive)
    sell_orders: Dict[int, int] = field(default_factory=dict)   # price → qty (negative)


@dataclass
class Trade:
    symbol:    Symbol
    price:     float
    quantity:  int
    buyer:     str = ""
    seller:    str = ""
    timestamp: int = 0


@dataclass
class ConversionObservation:
    bidPrice:       float = 0
    askPrice:       float = 0
    transportFees:  float = 0
    exportTariff:   float = 0
    importTariff:   float = 0
    sunlight:       float = 0
    humidity:       float = 0


@dataclass
class Observation:
    plainValueObservations:  Dict[str, float] = field(default_factory=dict)
    conversionObservations:  Dict[str, ConversionObservation] = field(default_factory=dict)


@dataclass
class Listing:
    symbol:       Symbol
    product:      Product
    denomination: str


@dataclass
class TradingState:
    traderData:    str
    timestamp:     int
    listings:      Dict[Symbol, Listing]
    order_depths:  Dict[Symbol, OrderDepth]
    own_trades:    Dict[Symbol, List[Trade]]
    market_trades: Dict[Symbol, List[Trade]]
    position:      Dict[Product, Position]
    observations:  Observation


class ProsperityEncoder(json.JSONEncoder):
    def default(self, o):
        if hasattr(o, "__dict__"):
            return o.__dict__
        return super().default(o)


# Inject into sys.modules so `from datamodel import ...` works
_datamodel_module = type(sys)("datamodel")
for _name in ["Order", "OrderDepth", "Trade", "TradingState", "Listing",
              "Observation", "ConversionObservation", "ProsperityEncoder",
              "Symbol", "Product", "Position"]:
    setattr(_datamodel_module, _name, globals()[_name])
sys.modules["datamodel"] = _datamodel_module


# ─────────────────────────────────────────────────────────────────────────────
#  DATA LOADING
# ─────────────────────────────────────────────────────────────────────────────

PRODUCTS = ["ASH_COATED_OSMIUM", "INTARIAN_PEPPER_ROOT"]
POSITION_LIMIT = 80
PRICE_COLS = {
    "bids": [("bid_price_1","bid_volume_1"),("bid_price_2","bid_volume_2"),("bid_price_3","bid_volume_3")],
    "asks": [("ask_price_1","ask_volume_1"),("ask_price_2","ask_volume_2"),("ask_price_3","ask_volume_3")],
}


def load_data(data_dir: str, days: List[int]) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Load and concatenate all price and trade CSVs."""
    price_frames, trade_frames = [], []
    for day in days:
        p = Path(data_dir) / f"prices_round_2_day_{day}.csv"
        t = Path(data_dir) / f"trades_round_2_day_{day}.csv"
        if not p.exists():
            raise FileNotFoundError(f"Missing: {p}")
        if not t.exists():
            raise FileNotFoundError(f"Missing: {t}")
        pdf = pd.read_csv(p, sep=";")
        tdf = pd.read_csv(t, sep=";")
        tdf["day"] = day
        price_frames.append(pdf)
        trade_frames.append(tdf)

    prices = pd.concat(price_frames, ignore_index=True)
    trades = pd.concat(trade_frames, ignore_index=True)
    prices.sort_values(["day", "timestamp", "product"], inplace=True)
    trades.sort_values(["day", "timestamp"], inplace=True)
    return prices, trades


def build_order_depth(row: pd.Series) -> OrderDepth:
    """Build an OrderDepth from a single price-CSV row."""
    od = OrderDepth()
    for pc, vc in PRICE_COLS["bids"]:
        p, v = row.get(pc), row.get(vc)
        if pd.notna(p) and pd.notna(v) and v > 0:
            od.buy_orders[int(p)] = int(v)
    for pc, vc in PRICE_COLS["asks"]:
        p, v = row.get(pc), row.get(vc)
        if pd.notna(p) and pd.notna(v) and v > 0:
            od.sell_orders[int(p)] = -int(v)  # sell_orders hold NEGATIVE qty
    return od


# ─────────────────────────────────────────────────────────────────────────────
#  ALGO LOADER
# ─────────────────────────────────────────────────────────────────────────────

def load_algo(algo_path: str):
    """Dynamically load the Trader class from any .py file."""
    spec = importlib.util.spec_from_file_location("trader_module", algo_path)
    mod  = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(mod)
    except Exception as e:
        raise ImportError(f"Failed to load algo '{algo_path}': {e}") from e
    if not hasattr(mod, "Trader"):
        raise AttributeError(f"'{algo_path}' has no class Trader")
    return mod.Trader


# ─────────────────────────────────────────────────────────────────────────────
#  LOG FILE PARSER
# ─────────────────────────────────────────────────────────────────────────────

def load_log(log_path: str) -> dict:
    """Parse a Prosperity .log JSON file."""
    with open(log_path) as f:
        data = json.load(f)

    trades_by_ts: Dict[int, List[dict]] = defaultdict(list)
    for t in data.get("tradeHistory", []):
        trades_by_ts[t["timestamp"]].append(t)

    # Parse activitiesLog into a DataFrame
    raw = data.get("activitiesLog", "")
    acts = pd.read_csv(io.StringIO(raw), sep=";") if raw.strip() else pd.DataFrame()

    return {
        "submission_id": data.get("submissionId", ""),
        "trades_by_ts":  trades_by_ts,
        "activities":    acts,
        "raw":           data,
    }


# ─────────────────────────────────────────────────────────────────────────────
#  ORDER MATCHING ENGINE
# ─────────────────────────────────────────────────────────────────────────────

class MatchingEngine:
    """
    Matches a list of Orders against the current order book.
    Rules:
      - Positive qty = buy order. Matches against sell_orders (asks).
      - Negative qty = sell order. Matches against buy_orders (bids).
      - If order price crosses the market (aggressive), fill at MARKET price.
      - If order price is passive (inside the spread), fill only if market moves.
      - Position limits enforced; excess qty silently dropped.
      - Multiple orders for same symbol: processed in list order.
    Returns list of Trade objects and updated positions.
    """

    def __init__(self, position_limits: Dict[str, int]):
        self.position_limits = position_limits

    def match(
        self,
        orders:    Dict[str, List[Order]],
        depths:    Dict[str, OrderDepth],
        positions: Dict[str, int],
        timestamp: int,
    ) -> Tuple[List[Trade], Dict[str, int], float]:
        """Returns (fills, new_positions, realized_cash_delta)."""
        fills      : List[Trade] = []
        new_pos     = dict(positions)
        cash_delta  = 0.0

        for symbol, order_list in orders.items():
            if symbol not in depths:
                continue
            od    = depths[symbol]
            limit = self.position_limits.get(symbol, POSITION_LIMIT)

            for order in order_list:
                qty  = order.quantity
                price = order.price
                pos   = new_pos.get(symbol, 0)

                if qty == 0:
                    continue

                if qty > 0:  # BUY — matches asks
                    # Clip to position limit
                    max_buy = limit - pos
                    qty = min(qty, max_buy)
                    if qty <= 0:
                        continue

                    filled = 0
                    # Sort asks low→high and fill greedily
                    for ask_price in sorted(od.sell_orders.keys()):
                        if filled >= qty:
                            break
                        if ask_price > price:        # passive: don't cross
                            break
                        avail   = -od.sell_orders[ask_price]  # positive vol
                        can_buy = min(avail, qty - filled)
                        if can_buy > 0:
                            fill_price = ask_price  # fill at market (better for us)
                            fills.append(Trade(symbol, fill_price, can_buy,
                                               "SUBMISSION", "", timestamp))
                            cash_delta  -= fill_price * can_buy
                            new_pos[symbol] = new_pos.get(symbol, 0) + can_buy
                            filled      += can_buy

                else:  # SELL — matches bids (qty negative)
                    sell_qty = -qty
                    max_sell  = limit + pos  # how much we can sell short to
                    sell_qty  = min(sell_qty, max_sell)
                    if sell_qty <= 0:
                        continue

                    filled = 0
                    for bid_price in sorted(od.buy_orders.keys(), reverse=True):
                        if filled >= sell_qty:
                            break
                        if bid_price < price:        # passive: don't cross
                            break
                        avail    = od.buy_orders[bid_price]
                        can_sell = min(avail, sell_qty - filled)
                        if can_sell > 0:
                            fill_price = bid_price
                            fills.append(Trade(symbol, fill_price, -can_sell,
                                               "", "SUBMISSION", timestamp))
                            cash_delta  += fill_price * can_sell
                            new_pos[symbol] = new_pos.get(symbol, 0) - can_sell
                            filled       += can_sell

        return fills, new_pos, cash_delta


# ─────────────────────────────────────────────────────────────────────────────
#  CORE BACKTEST LOOP
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class TickResult:
    day:           int
    timestamp:     int
    position:      Dict[str, int]
    cash:          float
    mark_to_market: float        # unrealized PnL from open positions
    realized_pnl:  float         # cumulative cash PnL
    total_pnl:     float         # realized + MTM
    fills:         List[Trade]
    trader_data:   str
    algo_error:    Optional[str]


def mid_price_from_depth(od: OrderDepth) -> float:
    best_bid = max(od.buy_orders.keys())  if od.buy_orders  else None
    best_ask = min(od.sell_orders.keys()) if od.sell_orders else None
    if best_bid and best_ask:
        return (best_bid + best_ask) / 2
    return best_bid or best_ask or 0.0


def run_backtest(
    TraderClass,
    prices:    pd.DataFrame,
    trades:    pd.DataFrame,
    days:      List[int],
    maf:       float = 0,
    verbose:   bool  = False,
) -> Tuple[List[TickResult], dict]:
    """
    Main backtest loop. Returns tick-by-tick results and a summary dict.
    """
    trader    = TraderClass()
    engine    = MatchingEngine({p: POSITION_LIMIT for p in PRODUCTS})

    positions : Dict[str, int]   = {p: 0 for p in PRODUCTS}
    cash       = 0.0
    trader_data = ""

    # Check if the algo has a bid() method (MAF)
    algo_maf = 0
    if hasattr(trader, "bid") and callable(trader.bid):
        try:
            algo_maf = float(trader.bid())
        except Exception:
            algo_maf = 0

    if maf > 0:
        algo_maf = maf   # command-line override

    # Group price rows by (day, timestamp) for fast lookup
    price_index = prices.groupby(["day", "timestamp"])

    # Build a sorted list of all unique (day, timestamp) ticks
    all_ticks = sorted(prices[["day","timestamp"]].drop_duplicates().itertuples(index=False),
                       key=lambda r: (r.day, r.timestamp))

    # Trade lookup: market trades at each (day, timestamp)
    trade_index = trades.groupby(["day","timestamp"])

    tick_results: List[TickResult] = []
    summary_fills: List[Trade] = []
    own_trades_acc: Dict[str, List[Trade]] = defaultdict(list)

    listings = {p: Listing(p, p, "XIRECS") for p in PRODUCTS}
    observations = Observation()

    for tick in all_ticks:
        day, ts = tick.day, tick.timestamp

        # Build OrderDepth for each product at this tick
        depths: Dict[str, OrderDepth] = {}
        try:
            tick_rows = price_index.get_group((day, ts))
        except KeyError:
            continue

        for _, row in tick_rows.iterrows():
            depths[row["product"]] = build_order_depth(row)

        # Build market_trades for this tick
        market_trades_tick: Dict[str, List[Trade]] = defaultdict(list)
        try:
            tick_trades = trade_index.get_group((day, ts))
            for _, tr in tick_trades.iterrows():
                market_trades_tick[tr["symbol"]].append(
                    Trade(tr["symbol"], tr["price"], tr["quantity"],
                          str(tr.get("buyer", "")), str(tr.get("seller", "")), ts)
                )
        except KeyError:
            pass

        # Build TradingState
        state = TradingState(
            traderData    = trader_data,
            timestamp     = ts,
            listings      = listings,
            order_depths  = {sym: copy.deepcopy(d) for sym, d in depths.items()},
            own_trades    = dict(own_trades_acc),
            market_trades = dict(market_trades_tick),
            position      = dict(positions),
            observations  = observations,
        )

        # Call the algo
        algo_error = None
        result_orders: Dict[str, List[Order]] = {}
        conversions = 0

        try:
            ret = trader.run(state)
            if isinstance(ret, tuple) and len(ret) == 3:
                result_orders, conversions, trader_data = ret
            elif isinstance(ret, tuple) and len(ret) == 2:
                result_orders, conversions = ret
            elif isinstance(ret, dict):
                result_orders = ret
        except Exception as e:
            algo_error = f"t={ts}: {type(e).__name__}: {e}"
            if verbose:
                traceback.print_exc()

        # Clear own_trades for next tick
        own_trades_acc = defaultdict(list)

        # Match orders
        if result_orders:
            fills, positions, delta = engine.match(
                result_orders, depths, positions, ts
            )
            cash += delta
            for f in fills:
                own_trades_acc[f.symbol].append(f)
                summary_fills.append(f)

            if verbose and fills:
                for f in fills:
                    side = "BUY" if f.quantity > 0 else "SELL"
                    print(f"  [{day}|{ts:>7}] {side} {abs(f.quantity):>3}x "
                          f"{f.symbol:<25} @{f.price:.1f}")
        else:
            fills = []

        # Mark-to-market
        mtm = 0.0
        for sym, pos in positions.items():
            od = depths.get(sym, OrderDepth())
            mid = mid_price_from_depth(od)
            mtm += pos * mid

        total_pnl = cash + mtm

        tick_results.append(TickResult(
            day=day, timestamp=ts,
            position=dict(positions),
            cash=cash,
            mark_to_market=mtm,
            realized_pnl=cash,
            total_pnl=total_pnl,
            fills=fills,
            trader_data=trader_data,
            algo_error=algo_error,
        ))

    # Final PnL (mark at last tick mid prices)
    final_pnl = tick_results[-1].total_pnl if tick_results else 0.0
    net_pnl   = final_pnl - algo_maf

    # Per-product fill stats
    product_stats: Dict[str, dict] = {}
    for sym in PRODUCTS:
        sym_fills = [f for f in summary_fills if f.symbol == sym]
        buys  = [f for f in sym_fills if f.quantity > 0]
        sells = [f for f in sym_fills if f.quantity < 0]
        buy_qty   = sum(f.quantity        for f in buys)
        sell_qty  = sum(-f.quantity       for f in sells)
        buy_cost  = sum(f.price*f.quantity for f in buys)
        sell_rev  = sum(f.price*-f.quantity for f in sells)
        avg_buy   = buy_cost  / buy_qty   if buy_qty   else 0
        avg_sell  = sell_rev  / sell_qty  if sell_qty  else 0
        product_stats[sym] = dict(
            buy_trades=len(buys), sell_trades=len(sells),
            buy_qty=buy_qty, sell_qty=sell_qty,
            avg_buy=avg_buy, avg_sell=avg_sell,
            net_qty=buy_qty - sell_qty,
        )

    summary = dict(
        algo_maf=algo_maf,
        gross_pnl=final_pnl,
        net_pnl=net_pnl,
        total_fills=len(summary_fills),
        product_stats=product_stats,
        final_positions=dict(positions),
        errors=[r.algo_error for r in tick_results if r.algo_error],
        pnl_series=[(r.day, r.timestamp, r.total_pnl) for r in tick_results],
    )
    return tick_results, summary


# ─────────────────────────────────────────────────────────────────────────────
#  LOG COMPARISON
# ─────────────────────────────────────────────────────────────────────────────

def compare_with_log(tick_results: List[TickResult], log_data: dict) -> dict:
    """
    Compare backtest PnL curve against the submitted log's PnL curve.
    Returns comparison statistics.
    """
    acts = log_data.get("activities", pd.DataFrame())
    if acts.empty:
        return {"error": "No activitiesLog in log file"}

    # Build log PnL series: last pnl per (day, timestamp) across products
    log_pnl: Dict[Tuple, float] = {}
    for _, row in acts.iterrows():
        key = (int(row["day"]), int(row["timestamp"]))
        log_pnl[key] = log_pnl.get(key, 0) + row.get("profit_and_loss", 0)

    # Build backtest series
    bt_pnl = {(r.day, r.timestamp): r.total_pnl for r in tick_results}

    common_keys = sorted(set(log_pnl) & set(bt_pnl))
    if not common_keys:
        return {"error": "No overlapping timestamps between log and backtest"}

    log_vals = [log_pnl[k] for k in common_keys]
    bt_vals  = [bt_pnl[k]  for k in common_keys]
    diffs    = [b - l for b, l in zip(bt_vals, log_vals)]

    # Log final PnL
    log_submission_trades = log_data.get("trades_by_ts", {})
    log_trade_count = sum(len(v) for v in log_submission_trades.values())
    log_final_pnl = log_vals[-1] if log_vals else 0
    bt_final_pnl  = bt_vals[-1]  if bt_vals  else 0

    return dict(
        common_ticks=len(common_keys),
        log_final_pnl=log_final_pnl,
        bt_final_pnl=bt_final_pnl,
        pnl_diff=bt_final_pnl - log_final_pnl,
        mean_abs_diff=float(np.mean(np.abs(diffs))),
        max_abs_diff=float(np.max(np.abs(diffs))),
        log_trade_count=log_trade_count,
        diffs_series=list(zip([str(k) for k in common_keys], diffs)),
    )


# ─────────────────────────────────────────────────────────────────────────────
#  MANUAL CHALLENGE OPTIMISER  (Invest & Expand)
# ─────────────────────────────────────────────────────────────────────────────

def optimise_investment(
    budget: float = 50_000,
    num_players: int = 50,
    our_rank_assumption: int = 25,   # assumed rank (1=fastest, N=slowest)
) -> dict:
    """
    Maximise: research(r%) * scale(s%) * speed_mult(rank) - budget_used
    where r + s + speed_pct <= 100, all in [0, 100].

    Speed multiplier is rank-based. We model it as a continuous function
    by assuming our rank proportional to our investment.
    """
    results = []
    steps = 200
    for r in range(0, steps + 1):
        for s in range(0, steps - r + 1):
            sp = steps - r - s
            r_pct  = r  / steps * 100
            s_pct  = s  / steps * 100
            sp_pct = sp / steps * 100

            research = 200_000 * np.log(1 + r_pct) / np.log(1 + 100)
            scale    = 7 * s_pct / 100

            # Speed rank assumption: linear interpolation
            # If we invest sp_pct, and opponents are uniform [0,100],
            # our rank ≈ fraction of players below us = sp_pct/100
            speed_rank_frac = sp_pct / 100   # 0=lowest, 1=highest
            speed_mult = 0.1 + 0.8 * speed_rank_frac  # 0.1 → 0.9

            gross   = research * scale * speed_mult
            budget_used = (r_pct + s_pct + sp_pct) / 100 * budget
            net     = gross - budget_used
            results.append((net, r_pct, s_pct, sp_pct, gross, budget_used, speed_mult))

    results.sort(reverse=True)
    best = results[0]
    return dict(
        net_pnl=best[0],
        research_pct=best[1],
        scale_pct=best[2],
        speed_pct=best[3],
        gross_pnl=best[4],
        budget_used=best[5],
        speed_mult=best[6],
        top_10=results[:10],
    )


# ─────────────────────────────────────────────────────────────────────────────
#  TERMINAL REPORT
# ─────────────────────────────────────────────────────────────────────────────

BOLD   = "\033[1m"
GREEN  = "\033[32m"
RED    = "\033[31m"
YELLOW = "\033[33m"
CYAN   = "\033[36m"
DIM    = "\033[2m"
RESET  = "\033[0m"

def color_pnl(v: float) -> str:
    s = f"{v:>+14,.1f}"
    return (GREEN if v >= 0 else RED) + s + RESET


def print_header(title: str):
    width = 72
    print()
    print(BOLD + CYAN + "═" * width + RESET)
    print(BOLD + CYAN + f"  {title}" + RESET)
    print(BOLD + CYAN + "═" * width + RESET)


def print_section(title: str):
    print()
    print(BOLD + f"  ── {title} ──" + RESET)


def print_report(
    algo_path:   str,
    summary:     dict,
    comparison:  Optional[dict],
    investment:  dict,
    log_path:    Optional[str],
    tick_results: List[TickResult],
):
    print_header(f"BACKTEST REPORT  ·  {Path(algo_path).name}")

    # ── PnL Summary ──────────────────────────────────────────────────────────
    print_section("PnL Summary")
    gross = summary["gross_pnl"]
    maf   = summary["algo_maf"]
    net   = summary["net_pnl"]

    print(f"  {'Gross PnL (before MAF):':<35} {color_pnl(gross)}")
    if maf > 0:
        print(f"  {'Market Access Fee (MAF):':<35} {RED}-{maf:>13,.1f}{RESET}")
    print(f"  {'Net PnL:':<35} {color_pnl(net)}")
    target = 200_000
    pct_of_target = net / target * 100
    bar_len = int(min(pct_of_target, 100) / 2)
    bar = "█" * bar_len + "░" * (50 - bar_len)
    color = GREEN if net >= target else (YELLOW if net >= target * 0.5 else RED)
    print(f"  {'Progress to 200k:':<35} {color}[{bar}] {pct_of_target:.1f}%{RESET}")

    # ── Per-Product Stats ─────────────────────────────────────────────────────
    print_section("Per-Product Fill Statistics")
    for sym, stats in summary["product_stats"].items():
        short = sym.replace("_", " ").title()
        print(f"\n  {BOLD}{short}{RESET}")
        print(f"    Buy  trades : {stats['buy_trades']:>6}   total qty: {stats['buy_qty']:>7}   avg price: {stats['avg_buy']:>10.2f}")
        print(f"    Sell trades : {stats['sell_trades']:>6}   total qty: {stats['sell_qty']:>7}   avg price: {stats['avg_sell']:>10.2f}")
        net_pos   = stats['net_qty']
        final_pos = summary['final_positions'].get(sym, 0)
        print(f"    Net position: {net_pos:>+6}   (final: {final_pos:>+4})")

    print(f"\n  Total fills: {summary['total_fills']}")

    # ── PnL Curve (sparkline) ─────────────────────────────────────────────────
    print_section("PnL Curve (sparkline, each char = ~300 ticks)")
    series = [v for _, _, v in summary["pnl_series"]]
    if series:
        n_chars = 60
        step = max(1, len(series) // n_chars)
        sampled = series[::step]
        lo, hi = min(sampled), max(sampled)
        rng = hi - lo if hi != lo else 1
        blocks = " ▁▂▃▄▅▆▇█"
        sparkline = ""
        for v in sampled:
            idx = int((v - lo) / rng * (len(blocks) - 1))
            sparkline += blocks[idx]
        print(f"  {DIM}PnL low: {lo:,.0f}  high: {hi:,.0f}{RESET}")
        print(f"  {CYAN}{sparkline}{RESET}")

    # ── Day Breakdown ─────────────────────────────────────────────────────────
    print_section("Per-Day PnL")
    day_pnl: Dict[int, float] = {}
    day_start: Dict[int, float] = {}
    for r in tick_results:
        if r.day not in day_start:
            day_start[r.day] = r.total_pnl
        day_pnl[r.day] = r.total_pnl

    prev = 0.0
    for d in sorted(day_pnl.keys()):
        end = day_pnl[d]
        delta = end - prev
        print(f"  Day {d:>+2}: end PnL = {color_pnl(end)}   Δ this day = {color_pnl(delta)}")
        prev = end

    # ── Error Summary ─────────────────────────────────────────────────────────
    errors = summary["errors"]
    if errors:
        print_section(f"⚠  Algo Errors ({len(errors)} ticks)")
        for e in errors[:10]:
            print(f"  {RED}{e}{RESET}")
        if len(errors) > 10:
            print(f"  {DIM}... and {len(errors)-10} more{RESET}")

    # ── Log Comparison ────────────────────────────────────────────────────────
    if comparison:
        print_section(f"Log Comparison  [{Path(log_path).name}]")
        if "error" in comparison:
            print(f"  {RED}{comparison['error']}{RESET}")
        else:
            lf = comparison["log_final_pnl"]
            bf = comparison["bt_final_pnl"]
            diff = comparison["pnl_diff"]
            print(f"  {'Submitted log final PnL:':<35} {color_pnl(lf)}")
            print(f"  {'Backtest final PnL:':<35} {color_pnl(bf)}")
            print(f"  {'Difference (bt - log):':<35} {color_pnl(diff)}")
            print(f"  {'Mean |diff| per tick:':<35} {comparison['mean_abs_diff']:>14.2f}")
            print(f"  {'Max  |diff| per tick:':<35} {comparison['max_abs_diff']:>14.2f}")
            print(f"  {'Log submission trades:':<35} {comparison['log_trade_count']:>14}")
            if abs(diff) < 500:
                print(f"  {GREEN}✓ Backtest closely matches submitted log{RESET}")
            elif abs(diff) < 5000:
                print(f"  {YELLOW}⚠ Moderate divergence — possible fill model differences{RESET}")
            else:
                print(f"  {RED}✗ Large divergence — check fill model / order logic{RESET}")

    # ── MAF Analysis ──────────────────────────────────────────────────────────
    print_section("Market Access Fee (MAF) Analysis")
    base_pnl = gross
    with_maf  = base_pnl * 1.25   # +25% volume approx
    maf_uplift = with_maf - base_pnl
    break_even_maf = maf_uplift
    print(f"  {'Estimated gross PnL (no MAF):':<40} {color_pnl(base_pnl)}")
    print(f"  {'Estimated gross PnL (+25% volume):':<40} {color_pnl(with_maf)}")
    print(f"  {'Incremental value of MAF:':<40} {color_pnl(maf_uplift)}")
    print(f"  {'Break-even MAF:':<40} {YELLOW}{break_even_maf:>+14,.1f}{RESET}")
    if maf > 0:
        if maf < break_even_maf:
            print(f"  {GREEN}✓ Your MAF ({maf:,.0f}) is below break-even — profitable if accepted{RESET}")
        else:
            print(f"  {RED}✗ Your MAF ({maf:,.0f}) exceeds break-even — reconsider{RESET}")
    else:
        print(f"  {DIM}No MAF set. Recommend bidding up to {break_even_maf:,.0f}{RESET}")

    # ── Investment Optimiser ──────────────────────────────────────────────────
    print_section("Manual Challenge: Invest & Expand (50,000 budget)")
    inv = investment
    print(f"  {BOLD}Optimal allocation:{RESET}")
    print(f"    Research : {inv['research_pct']:>5.1f}%")
    print(f"    Scale    : {inv['scale_pct']:>5.1f}%")
    print(f"    Speed    : {inv['speed_pct']:>5.1f}%")
    print(f"    Budget used: {inv['budget_used']:>10,.0f}  (speed mult assumed: {inv['speed_mult']:.2f})")
    print(f"    Gross manual PnL: {color_pnl(inv['gross_pnl'])}")
    print(f"    Net   manual PnL: {color_pnl(inv['net_pnl'])}")
    print()
    print(f"  {DIM}Note: Speed multiplier is rank-based; actual result depends on")
    print(f"  competitors' speed investments. Maximise Research × Scale first,{RESET}")
    print(f"  {DIM}then invest remaining budget in Speed to stay competitive.{RESET}")

    print()
    print(BOLD + CYAN + "═" * 72 + RESET)
    print()


# ─────────────────────────────────────────────────────────────────────────────
#  HTML REPORT
# ─────────────────────────────────────────────────────────────────────────────

def save_html_report(
    path: str,
    algo_path: str,
    summary: dict,
    comparison: Optional[dict],
    investment: dict,
    tick_results: List[TickResult],
):
    pnl_series = summary["pnl_series"]
    days_  = [d for d, _, _ in pnl_series]
    ticks_ = [t for _, t, _ in pnl_series]
    pnls_  = [v for _, _, v in pnl_series]

    # Build global tick index for x-axis
    global_t = [
        (d + 1) * 1_000_000 + t
        for d, t in zip(days_, ticks_)
    ]

    fill_ts   = [(r.day + 1) * 1_000_000 + r.timestamp for r in tick_results for _ in r.fills]
    fill_pnls = [r.total_pnl for r in tick_results for _ in r.fills]

    gross   = summary["gross_pnl"]
    maf     = summary["algo_maf"]
    net     = summary["net_pnl"]
    inv     = investment
    errors  = summary["errors"]
    comp    = comparison or {}

    product_rows = ""
    for sym, st in summary["product_stats"].items():
        product_rows += f"""
        <tr>
          <td>{sym}</td>
          <td>{st['buy_qty']}</td><td>{st['avg_buy']:.2f}</td>
          <td>{st['sell_qty']}</td><td>{st['avg_sell']:.2f}</td>
          <td>{st['net_qty']:+d}</td>
        </tr>"""

    comp_html = ""
    if comp and "error" not in comp:
        diff_color = "green" if abs(comp['pnl_diff']) < 500 else ("orange" if abs(comp['pnl_diff']) < 5000 else "red")
        comp_html = f"""
        <h2>Log Comparison</h2>
        <table>
          <tr><th>Metric</th><th>Value</th></tr>
          <tr><td>Log final PnL</td><td>{comp['log_final_pnl']:+,.1f}</td></tr>
          <tr><td>Backtest final PnL</td><td>{comp['bt_final_pnl']:+,.1f}</td></tr>
          <tr><td>Difference</td><td style="color:{diff_color}">{comp['pnl_diff']:+,.1f}</td></tr>
          <tr><td>Mean |diff|/tick</td><td>{comp['mean_abs_diff']:.2f}</td></tr>
          <tr><td>Max  |diff|/tick</td><td>{comp['max_abs_diff']:.2f}</td></tr>
        </table>"""

    error_html = ""
    if errors:
        error_html = "<h2>Algo Errors</h2><ul>" + \
            "".join(f"<li><code>{e}</code></li>" for e in errors[:20]) + "</ul>"

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Backtest — {Path(algo_path).name}</title>
<script src="https://cdn.plot.ly/plotly-2.29.1.min.js"></script>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; background:#0e1117; color:#e6edf3; margin:0; padding:24px; }}
  h1 {{ color:#58a6ff; border-bottom:1px solid #30363d; padding-bottom:8px; }}
  h2 {{ color:#79c0ff; margin-top:28px; }}
  table {{ border-collapse:collapse; width:100%; margin-top:8px; }}
  th,td {{ border:1px solid #30363d; padding:8px 12px; text-align:right; }}
  th {{ background:#161b22; color:#79c0ff; text-align:center; }}
  td:first-child {{ text-align:left; }}
  .stat-grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(200px,1fr)); gap:16px; margin:16px 0; }}
  .stat-box {{ background:#161b22; border:1px solid #30363d; border-radius:8px; padding:16px; }}
  .stat-label {{ font-size:12px; color:#8b949e; }}
  .stat-value {{ font-size:24px; font-weight:700; margin-top:4px; }}
  .green {{ color:#3fb950; }} .red {{ color:#f85149; }} .yellow {{ color:#d29922; }}
  #chart {{ width:100%; height:420px; }}
  code {{ background:#161b22; padding:2px 6px; border-radius:4px; font-size:13px; }}
</style>
</head>
<body>
<h1>📊 Backtest Report · {Path(algo_path).name}</h1>

<div class="stat-grid">
  <div class="stat-box">
    <div class="stat-label">Gross PnL</div>
    <div class="stat-value {'green' if gross>=0 else 'red'}">{gross:+,.0f}</div>
  </div>
  <div class="stat-box">
    <div class="stat-label">MAF Paid</div>
    <div class="stat-value yellow">{maf:,.0f}</div>
  </div>
  <div class="stat-box">
    <div class="stat-label">Net PnL</div>
    <div class="stat-value {'green' if net>=0 else 'red'}">{net:+,.0f}</div>
  </div>
  <div class="stat-box">
    <div class="stat-label">Target (200k)</div>
    <div class="stat-value {'green' if net>=200000 else 'yellow'}">{net/200000*100:.1f}%</div>
  </div>
  <div class="stat-box">
    <div class="stat-label">Total Fills</div>
    <div class="stat-value">{summary['total_fills']}</div>
  </div>
  <div class="stat-box">
    <div class="stat-label">Errors</div>
    <div class="stat-value {'red' if errors else 'green'}">{len(errors)}</div>
  </div>
</div>

<div id="chart"></div>
<script>
var x = {json.dumps(global_t)};
var y = {json.dumps(pnls_)};
var fx = {json.dumps(fill_ts)};
var fy = {json.dumps(fill_pnls)};
Plotly.newPlot('chart', [
  {{ x:x, y:y, type:'scatter', mode:'lines', name:'PnL',
     line:{{color:'#58a6ff', width:2}},
     fill:'tozeroy', fillcolor:'rgba(88,166,255,0.1)' }},
  {{ x:fx, y:fy, type:'scatter', mode:'markers', name:'Fill',
     marker:{{color:'#3fb950', size:4, symbol:'circle'}} }},
  {{ x:[x[0],x[x.length-1]], y:[200000,200000], type:'scatter', mode:'lines',
     name:'200k Target', line:{{color:'#d29922', dash:'dash', width:1}} }},
  {{ x:[x[0],x[x.length-1]], y:[0,0], type:'scatter', mode:'lines',
     name:'Break-even', line:{{color:'#f85149', dash:'dot', width:1}} }}
], {{
  paper_bgcolor:'#0e1117', plot_bgcolor:'#0e1117',
  font:{{color:'#e6edf3'}},
  xaxis:{{title:'Global Tick (day × 1M + timestamp)', gridcolor:'#21262d'}},
  yaxis:{{title:'PnL (XIRECs)', gridcolor:'#21262d'}},
  legend:{{bgcolor:'#161b22', bordercolor:'#30363d', borderwidth:1}},
  margin:{{t:20,b:50,l:80,r:20}}
}});
</script>

<h2>Fill Statistics by Product</h2>
<table>
  <tr><th>Product</th><th>Buy Qty</th><th>Avg Buy</th><th>Sell Qty</th><th>Avg Sell</th><th>Net Pos</th></tr>
  {product_rows}
</table>

{comp_html}

<h2>Investment Optimiser (Manual Challenge)</h2>
<table>
  <tr><th>Pillar</th><th>Allocation</th></tr>
  <tr><td>Research</td><td>{inv['research_pct']:.1f}%</td></tr>
  <tr><td>Scale</td><td>{inv['scale_pct']:.1f}%</td></tr>
  <tr><td>Speed</td><td>{inv['speed_pct']:.1f}%</td></tr>
  <tr><td>Budget used</td><td>{inv['budget_used']:,.0f} XIRECs</td></tr>
  <tr><td>Speed multiplier (assumed)</td><td>{inv['speed_mult']:.2f}</td></tr>
  <tr><td>Gross manual PnL</td><td>{inv['gross_pnl']:+,.0f}</td></tr>
  <tr><td><b>Net manual PnL</b></td><td><b>{inv['net_pnl']:+,.0f}</b></td></tr>
</table>

{error_html}

<p style="color:#8b949e;font-size:12px;margin-top:32px">
  Generated by Prosperity Backtest Engine · {Path(algo_path).name}
</p>
</body>
</html>"""

    with open(path, "w") as f:
        f.write(html)
    print(f"  {GREEN}HTML report saved → {path}{RESET}")


# ─────────────────────────────────────────────────────────────────────────────
#  CLI
# ─────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Prosperity Round 2 Backtesting Engine",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""
        Examples:
          # Basic backtest
          python backtest.py --algo trader.py

          # Backtest + compare against submission log
          python backtest.py --algo trader.py --log submission.log

          # Custom data directory + specific days + MAF override
          python backtest.py --algo trader.py --data-dir ./data --days -1 0 1 --maf 10000

          # Save HTML report
          python backtest.py --algo trader.py --log sub.log --report report.html

          # Verbose (print every fill)
          python backtest.py --algo trader.py --verbose
        """)
    )
    parser.add_argument("--algo",      required=True,  help="Path to your Trader .py file")
    parser.add_argument("--log",       default=None,   help="Path to submission .log JSON file for comparison")
    parser.add_argument("--data-dir",  default=".",    help="Directory containing the 6 CSV data files (default: .)")
    parser.add_argument("--days",      nargs="+", type=int, default=[-1, 0, 1], help="Days to simulate (default: -1 0 1)")
    parser.add_argument("--maf",       type=float, default=0, help="Override MAF value (0 = use algo's bid() if present)")
    parser.add_argument("--verbose",   action="store_true", help="Print every fill to stdout")
    parser.add_argument("--report",    default=None,   help="Save HTML report to this path")
    parser.add_argument("--no-color",  action="store_true", help="Disable terminal colours")
    args = parser.parse_args()

    if args.no_color:
        for name in ["BOLD","GREEN","RED","YELLOW","CYAN","DIM","RESET"]:
            globals()[name] = ""

    # ── Load data ─────────────────────────────────────────────────────────────
    print(f"{CYAN}Loading data from '{args.data_dir}' for days {args.days}…{RESET}")
    try:
        prices, trades = load_data(args.data_dir, args.days)
    except FileNotFoundError as e:
        print(f"{RED}Error: {e}{RESET}")
        sys.exit(1)
    print(f"  Loaded {len(prices):,} price rows, {len(trades):,} trade rows")

    # ── Load algo ─────────────────────────────────────────────────────────────
    print(f"{CYAN}Loading algo: {args.algo}{RESET}")
    try:
        TraderClass = load_algo(args.algo)
    except (ImportError, AttributeError) as e:
        print(f"{RED}Error: {e}{RESET}")
        sys.exit(1)
    print(f"  Trader class loaded ✓")

    # ── Load log (optional) ───────────────────────────────────────────────────
    log_data = None
    if args.log:
        print(f"{CYAN}Loading log: {args.log}{RESET}")
        try:
            log_data = load_log(args.log)
            ntrades = sum(len(v) for v in log_data["trades_by_ts"].values())
            print(f"  Log loaded: {ntrades} submission trades ✓")
        except Exception as e:
            print(f"{YELLOW}Warning: could not load log ({e}){RESET}")

    # ── Run backtest ──────────────────────────────────────────────────────────
    print(f"{CYAN}Running backtest ({len(prices):,} ticks)…{RESET}")
    tick_results, summary = run_backtest(
        TraderClass, prices, trades,
        days=args.days, maf=args.maf, verbose=args.verbose
    )
    print(f"  Done. {summary['total_fills']} fills, gross PnL = {summary['gross_pnl']:+,.1f}")

    # ── Compare with log ──────────────────────────────────────────────────────
    comparison = None
    if log_data:
        comparison = compare_with_log(tick_results, log_data)

    # ── Investment optimiser ──────────────────────────────────────────────────
    investment = optimise_investment()

    # ── Print terminal report ─────────────────────────────────────────────────
    print_report(
        algo_path=args.algo,
        summary=summary,
        comparison=comparison,
        investment=investment,
        log_path=args.log,
        tick_results=tick_results,
    )

    # ── Save HTML ─────────────────────────────────────────────────────────────
    if args.report:
        save_html_report(
            path=args.report,
            algo_path=args.algo,
            summary=summary,
            comparison=comparison,
            investment=investment,
            tick_results=tick_results,
        )

    # Exit code
    sys.exit(0 if summary["net_pnl"] > 0 else 1)


if __name__ == "__main__":
    main()
